In [2]:
import numpy as np

In [123]:
NUM_INPUTS = 2
weights = np.random.rand(1, NUM_INPUTS)
weights

array([[0.00410145, 0.34293512]])

$$
f(x) =
\begin{cases} 
1 & x \geq 1 \\
0 & x < 1
\end{cases}
$$

In [72]:
def step_function(z):
    return 1 if z >= 1 else 0

$$
z = \mathbf{X} \cdot \mathbf{W}^T
$$

$$
\hat{y} = f(z)
$$


In [73]:
def feed_forward(inputs, weights):
    z = inputs @ weights.T
    y_hat = step_function(z[0])
    return y_hat
    

### Treinamento do Perceptron (Algoritmo de Aprendizado)

**Inicialização:**
- Dado um conjunto de treinamento \( X \) e saídas desejadas \( y \).
- Definimos uma matriz de pesos \( W \) e uma taxa de aprendizado \( \eta \).

**Algoritmo de Aprendizado:**

1. Para cada época (repetir \( N \) vezes):
   - Para cada exemplo de treinamento \( x^{(i)} \) e \( y^{(i)} \):
     - Calcula-se a saída prevista:
       $$
       \hat{y}^{(i)} = f(X^{(i)} \cdot W^T)
       $$
     - Calcula-se o erro:
       $$
       \text{erro} = y^{(i)} - \hat{y}^{(i)}
       $$
     - Se o erro for maior que zero:
       - Atualiza os pesos:
         $$
         W_j = W_j + \eta \times x_j^{(i)} \times \text{erro}
         $$

2. Retorna a matriz de pesos \( W \) ajustada.


In [85]:
def fit(training_data, y, weights, learning_rate=0.1, epochs=10000):
    for _ in range(epochs):
        for i, data in enumerate(training_data):
            y_hat = feed_forward(data, weights)
            erro = y[i] - y_hat
            if abs(erro) > 0:
            
                for j in range(weights.shape[1]):
                    weights[0, j] = weights[0, j] + (learning_rate * data[0, j] * erro)
    return weights

In [96]:
training_data = [
    np.array([[1, 1]]),
    np.array([[1, 0]]),
    np.array([[0, 1]]),
    np.array([[0, 0]]),
]

y = [1, 0, 0, 0]
print(weights)
print(feed_forward(np.array([[1, 1]]), weights))
print('-' * 10)
weights = fit(training_data, y, weights)
print(weights)
print(feed_forward(np.array([[1, 1]]), weights))

[[0.58271868 0.02545736]]
0
----------
[[0.78271868 0.22545736]]
1


In [99]:
feed_forward(np.array([[0, 1]]), weights)

0

In [130]:
weights = np.random.rand(1, NUM_INPUTS)

training_data = [
    np.array([[100, 1]]),
    np.array([[250, 7]]),
    np.array([[190, 50]]),
    np.array([[255, 800]]),
    np.array([[300, 1800]]),
    np.array([[10, 70]])
]
y = [1, 1, 1, 0, 0, 0]

In [131]:
weights = fit(training_data, y, weights)

In [135]:
feed_forward(np.array([[210, 400]]), weights)

0